# This file enables the GitHub Sponsors button on your repository.
# For more details: https://docs.github.com/en/get-started/quickstart/funding-your-project-on-github
github: [ "https://github.com/sponsors/theyonecodes" ]
